# Generated by Django 4.2.5 on 2023-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_cartdetail_price_alter_cartdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
